// <auto-generated />
using DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126020449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelAcademicoId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("NivelAcademicos");
                });

            modelBuilder.Entity("DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Models.Curso", b =>
                {
                    b.HasOne("DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("DSW1_T1_PEREZ_RODRIGUEZ_ANTHONY_JORDAN.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
